apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp
spec:
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
      - name: reactapp
        image: arsom/reactapp-ci:7c14c14266667e7bee6bbf387eef29148aeaade8
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
